-- CreateTable
CREATE TABLE `Ropa` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `tipoRopa` VARCHAR(191) NOT NULL,
    `talla` VARCHAR(191) NOT NULL,
    `marca` VARCHAR(191) NOT NULL,
    `sexo` VARCHAR(191) NOT NULL,
    `color` VARCHAR(191) NOT NULL,
    `precio` DOUBLE NOT NULL,
    `stock` BOOLEAN NOT NULL DEFAULT false,
    `fechaSalida` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
